package com.paulchibamba.teleprompter.domain.model

/**
 * The three presets Prompter ships with (docs/SPEC.md §3.3).
 *
 * They are defined here, in `domain`, rather than as seed SQL, so the same values are used whether
 * a row is being inserted on first run or a test is asserting what "Bright room" means.
 *
 * Their ids are **fixed constants**, not autogenerated. A script's `presetId` refers to a preset by
 * id, so the id of a built-in has to be the same number on every install and after every reinstall
 * — an autogenerated one would only be stable by luck of insertion order. Seeding inserts these
 * rows with `OnConflictStrategy.IGNORE`, which makes re-running it a no-op and leaves any edits
 * alone; user presets autogenerate from [FIRST_USER_ID] upwards.
 */
object BuiltInPresets {

    const val STUDIO_ID = 1L
    const val BRIGHT_ROOM_ID = 2L
    const val TIGHT_GLASS_ID = 3L

    /** Room's `AUTOINCREMENT` hands out ids above the highest ever used, so this is where users start. */
    const val FIRST_USER_ID = 4L

    /** The everyday preset, and the shape the app's own defaults already take. */
    val studio = Preset(
        id = STUDIO_ID,
        name = "Studio",
        isBuiltIn = true,
        typography = TypographySettings(
            fontId = TypographySettings.DEFAULT_FONT_ID,
            sizeSp = 72f,
            lineHeightMul = 1.5f,
            textColor = WHITE,
            backgroundColor = BLACK,
        ),
        layout = LayoutSettings(
            marginLeftPct = 12f,
            marginRightPct = 12f,
            readingLinePct = 40f,
        ),
    )

    /** Daylight and a washed-out beam splitter: maximum contrast, heavier weight, open tracking. */
    val brightRoom = Preset(
        id = BRIGHT_ROOM_ID,
        name = "Bright room",
        isBuiltIn = true,
        typography = TypographySettings(
            fontId = TypographySettings.ATKINSON_FONT_ID,
            sizeSp = 88f,
            weight = 700,
            letterSpacingEm = 0.02f,
            textColor = WHITE,
            backgroundColor = BLACK,
        ),
        layout = LayoutSettings(
            marginLeftPct = 12f,
            marginRightPct = 12f,
            readingLinePct = 40f,
        ),
    )

    /** Small glass: smaller type, tighter leading and wide margins so nothing falls off the crop. */
    val tightGlass = Preset(
        id = TIGHT_GLASS_ID,
        name = "Tight glass",
        isBuiltIn = true,
        typography = TypographySettings(
            sizeSp = 56f,
            lineHeightMul = 1.35f,
            textColor = WHITE,
            backgroundColor = BLACK,
        ),
        layout = LayoutSettings(
            marginLeftPct = 22f,
            marginRightPct = 22f,
            readingLinePct = 50f,
        ),
    )

    val all: List<Preset> = listOf(studio, brightRoom, tightGlass)

    private const val WHITE = 0xFFFFFFFF
    private const val BLACK = 0xFF000000
}
