package com.paulchibamba.teleprompter.data.db

import com.paulchibamba.teleprompter.domain.model.BuiltInPresets
import com.paulchibamba.teleprompter.domain.model.Preset
import com.paulchibamba.teleprompter.domain.repository.PresetRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emitAll
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.map

/**
 * The Room-backed [PresetRepository].
 *
 * Seeding happens here, on first read, rather than in a `RoomDatabase.Callback` or in the migration
 * that creates the table. A callback fires on creation only, so an existing install upgrading to a
 * version that adds a fourth built-in would never see it, and the seed rows would have to be
 * written twice — once as Kotlin, once as SQL inside the migration — with no compiler to notice
 * when the two drift. Seeding on read is one implementation, always current, and idempotent.
 */
class RoomPresetRepository(private val dao: PresetDao) : PresetRepository {

    override fun observeAll(): Flow<List<Preset>> = flow {
        ensureBuiltIns()
        emitAll(dao.observeAll().map { entities -> entities.map(PresetEntity::toDomain) })
    }

    override suspend fun byId(id: Long): Preset? {
        ensureBuiltIns()
        return dao.byId(id)?.toDomain()
    }

    override suspend fun upsert(preset: Preset): Long {
        // Seed before inserting, not just before reading: the built-ins hold fixed ids 1..3, and an
        // autogenerated user preset written into an unseeded table would take one of them. The
        // built-in would then be silently ignored by every later seed attempt and never appear.
        ensureBuiltIns()
        val rowId = dao.upsert(preset.coerced().toEntity())
        // @Upsert returns -1 when the row was updated rather than inserted; the caller wants the
        // id it can refer to either way.
        return if (rowId == -1L) preset.id else rowId
    }

    override suspend fun delete(id: Long): Boolean = dao.deleteUserPreset(id) > 0

    override suspend fun ensureBuiltIns() {
        dao.insertIfAbsent(BuiltInPresets.all.map { it.toEntity() })
    }
}
